apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "tile38.fullname" . }}-leader
  labels:
    {{- include "tile38.componentLabels" (dict "ctx" . "component" "leader") | nindent 4 }}
spec:
  # Tile38 doesn't support multi master so replicas hardcoded.
  replicas: {{ .Values.leader.replicaCount }}
  revisionHistoryLimit: {{ .Values.leader.revisionHistoryLimit }}
  selector:
    matchLabels:
      {{- include "tile38.componentSelectorLabels" (dict "ctx" . "component" "leader") | nindent 6 }}
  {{- with .Values.leader.rolloutStrategy }}
  strategy:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  template:
    metadata:
      labels:
        {{- include "tile38.componentLabels" (dict "ctx" . "component" "leader") | nindent 8 }}
        {{- with .Values.global.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.leader.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/leader/leader-configmap.yaml") . | sha256sum }}
        {{- with .Values.global.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- with .Values.leader.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "tile38.serviceAccountName" . }}
      automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
      terminationGracePeriodSeconds: {{ .Values.leader.terminationGracePeriodSeconds }}
      {{- with .Values.leader.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
      {{- $podSec := default .Values.global.podSecurityContext .Values.leader.podSecurityContext }}
      {{- with $podSec }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.leader.config.enabled }}
      # We need to copy config before docker image runs.
      initContainers:
        - name: copy-config
          image: "{{ .Values.initContainerImage.repository }}:{{ .Values.initContainerImage.tag }}"
          imagePullPolicy: {{ .Values.initContainerImage.pullPolicy }}
          {{- $ctrSec := default .Values.global.securityContext .Values.leader.securityContext }}
          {{- with $ctrSec }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          command: ["sh", "-c", "cp /config /data/config"]
          volumeMounts:
            - name: leader-config-file
              mountPath: /config
              subPath: config
            - name: config
              mountPath: /data
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- $ctrSec := default .Values.global.securityContext .Values.leader.securityContext }}
          {{- with $ctrSec }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          command:
            - tile38-server
          args:
            - -h
            - "0.0.0.0"
            - -p
            - "{{ .Values.leader.service.tilePort }}"
            - -d
            - "/data"
            {{- if .Values.serviceMonitor.enabled }}
            - --metrics-addr
            - "0.0.0.0:{{ .Values.leader.service.monitoringPort }}"
            {{- end }}
            {{- range $key, $value := .Values.leader.extraArgs }}
            - {{ printf "--%s=%s" (kebabcase $key) $value }}
            {{- end }}
            {{- range .Values.leader.extraFlags }}
            - --{{ kebabcase . }}
            {{- end }}
          ports:
            - name: monitoring
              containerPort: {{ .Values.leader.service.monitoringPort }}
              protocol: TCP
            - name: tile
              containerPort: {{ .Values.leader.service.tilePort }}
              protocol: TCP
          {{- if .Values.leader.livenessProbe.enabled }}
          livenessProbe:
            tcpSocket:
              port: tile
            initialDelaySeconds: {{ .Values.leader.livenessProbe.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.leader.livenessProbe.timeoutSeconds }}
            periodSeconds: {{ .Values.leader.livenessProbe.periodSeconds }}
            failureThreshold: {{ .Values.leader.livenessProbe.failureThreshold }}
            successThreshold: {{ .Values.leader.livenessProbe.successThreshold }}
          {{- end }}
          {{- if .Values.leader.readinessProbe.enabled }}
          readinessProbe:
            tcpSocket:
              port: tile
            initialDelaySeconds: {{ .Values.leader.readinessProbe.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.leader.readinessProbe.timeoutSeconds }}
            periodSeconds: {{ .Values.leader.readinessProbe.periodSeconds }}
            failureThreshold: {{ .Values.leader.readinessProbe.failureThreshold }}
            successThreshold: {{ .Values.leader.readinessProbe.successThreshold }}
          {{- end }}
          {{- if .Values.leader.startupProbe.enabled }}
          startupProbe:
            tcpSocket:
              port: tile
            initialDelaySeconds: {{ .Values.leader.startupProbe.initialDelaySeconds }}
            timeoutSeconds: {{ .Values.leader.startupProbe.timeoutSeconds }}
            periodSeconds: {{ .Values.leader.startupProbe.periodSeconds }}
            failureThreshold: {{ .Values.leader.startupProbe.failureThreshold }}
            successThreshold: {{ .Values.leader.startupProbe.successThreshold }}
          {{- end }}
          resources:
            {{- toYaml .Values.leader.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /data
            {{- if .Values.leader.config.enabled }}
            - name: config
              mountPath: /data/config
              subPath: config
            {{- end }}
      {{- $nodeSelector := default .Values.global.nodeSelector .Values.leader.nodeSelector }}
      {{- with $nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- $affinity := default .Values.global.affinity .Values.leader.affinity }}
      {{- with $affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- $tolerations := default .Values.global.tolerations .Values.leader.tolerations }}
      {{- with $tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.leader.topologySpreadConstraints }}
      topologySpreadConstraints:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        {{- if .Values.leader.persistence.enabled }}
        - name: data
          persistentVolumeClaim:
            claimName: {{ .Values.leader.persistence.existingClaim | default (printf "%s-leader-pvc" (include "tile38.fullname" .)) }}
        {{- else }}
        - name: data
          emptyDir: {}
        {{- end }}
        {{- if .Values.leader.config.enabled }}
        - name: leader-config-file
          configMap:
            name: {{ include "tile38.fullname" . }}-leader-configs
            items:
              - key: config
                path: config
            defaultMode: 0644
        - name: config
          emptyDir: {}
        {{- end }}
