apiVersion: v1
kind: Service
metadata:
  name: {{ include "tile38.fullname" . }}-headless
  labels:
    {{- include "tile38.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: {{ .Values.service.port }}
      targetPort: tile
      protocol: TCP
      name: tile
  selector:
    {{- include "tile38.selectorLabels" . | nindent 4 }}
