apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "tile38.fullname" . }}
  labels:
    {{- include "tile38.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "tile38.fullname" . }}-headless
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "tile38.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "tile38.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "tile38.serviceAccountName" . }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - tile38-server
            - --metrics-addr
            - "127.0.0.1:4321"
            - --protected-mode
            - "{{ if .Values.flags.protectedMode }}yes{{ else }}no{{ end }}"
            - --appendonly
            - "{{ if .Values.flags.appendOnly }}yes{{ else }}no{{ end }}"
          ports:
            - name: monitoring
              containerPort: 4321
              protocol: TCP
            - name: tile
              containerPort: 9851
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 9851
            initialDelaySeconds: 30
            timeoutSeconds: 1
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 9851
            initialDelaySeconds: 10
            timeoutSeconds: 1
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: {{ .Values.server.storage.name }}
              mountPath: /data
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  volumeClaimTemplates:
    - metadata:
        name: {{ .Values.server.storage.name }}
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: {{ .Values.server.storage.type }}
        resources:
          requests:
            storage: {{ .Values.server.storage.size }}
