---
name: test

on:
  push: {}
  pull_request: {}

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: set up helm
        uses: azure/setup-helm@v5

      - uses: actions/setup-python@v6
        with:
          python-version: "3.13"

      - name: set up chart-testing
        uses: helm/chart-testing-action@v2.8.0

      - name: list changed charts
        id: list-changed
        run: |
          changed=$(ct list-changed --config ct.yaml --target-branch ${{ github.event.repository.default_branch }})
          if [[ -n "$changed" ]]; then
            echo "changed=true" >> "$GITHUB_OUTPUT"
          fi

      - name: run chart-testing (lint)
        run: ct lint --config ct.yaml --all

      - name: create kind cluster
        if: steps.list-changed.outputs.changed == 'true' || github.event_name == 'push'
        uses: helm/kind-action@v1.14.0

      - name: run chart-testing (install)
        if: steps.list-changed.outputs.changed == 'true' || github.event_name == 'push'
        run: ct install --config ct.yaml --all
